// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 17.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Paintc.Resources.RTT
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using Paintc.Shapes.C;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\Repositories\paintc2.0\Paintc2.0\Paintc\Resources\RTT\CLineTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public partial class CLineTemplate : BaseTemplate
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("﻿");
            this.Write("/* Code generated by Paintc */\r\n#include <graphics.h>\r\n#include <conio.h>\r\n\r\n/* D" +
                    "ibuja ");
            
            #line 11 "D:\Repositories\paintc2.0\Paintc2.0\Paintc\Resources\RTT\CLineTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(line.Name));
            
            #line default
            #line hidden
            this.Write(" */\r\nvoid draw");
            
            #line 12 "D:\Repositories\paintc2.0\Paintc2.0\Paintc\Resources\RTT\CLineTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(line.Name));
            
            #line default
            #line hidden
            this.Write(@"();

int main()
{
    int GraphDriver, GraphMode, ErrorCode;
    GraphDriver = DETECT; /* Request auto-detection	*/
    initgraph(&GraphDriver, &GraphMode, """");
    ErrorCode = graphresult(); /* Read result of initialization*/
    if (ErrorCode != grOk) /* Error occured during init	*/
    { 
        printf("" Graphics System Error: %s\n"", grapherrormsg(ErrorCode));
        exit(1);
    }

    /* Establecer color de fondo */
    setbkcolor(");
            
            #line 27 "D:\Repositories\paintc2.0\Paintc2.0\Paintc\Resources\RTT\CLineTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(settings.BackgroundColor));
            
            #line default
            #line hidden
            this.Write(");\r\n\r\n    /* Your code here... */\r\n    draw");
            
            #line 30 "D:\Repositories\paintc2.0\Paintc2.0\Paintc\Resources\RTT\CLineTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(line.Name));
            
            #line default
            #line hidden
            this.Write("();\r\n\r\n    getch();\r\n    closegraph(); /* Return the system to text mode\t*/\r\n    " +
                    "return 0;\r\n}\r\n\r\nvoid draw");
            
            #line 37 "D:\Repositories\paintc2.0\Paintc2.0\Paintc\Resources\RTT\CLineTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(line.Name));
            
            #line default
            #line hidden
            this.Write("()\r\n{\r\n    /* Coordenadas de la linea */\r\n    int x1 = ");
            
            #line 40 "D:\Repositories\paintc2.0\Paintc2.0\Paintc\Resources\RTT\CLineTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(line.X1));
            
            #line default
            #line hidden
            this.Write(", y1 = ");
            
            #line 40 "D:\Repositories\paintc2.0\Paintc2.0\Paintc\Resources\RTT\CLineTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(line.Y1));
            
            #line default
            #line hidden
            this.Write(", x2 = ");
            
            #line 40 "D:\Repositories\paintc2.0\Paintc2.0\Paintc\Resources\RTT\CLineTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(line.X2));
            
            #line default
            #line hidden
            this.Write(", y2 = ");
            
            #line 40 "D:\Repositories\paintc2.0\Paintc2.0\Paintc\Resources\RTT\CLineTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(line.Y2));
            
            #line default
            #line hidden
            this.Write(";\r\n\r\n    /* Estilos, colores... */\r\n    int lineStyle = ");
            
            #line 43 "D:\Repositories\paintc2.0\Paintc2.0\Paintc\Resources\RTT\CLineTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(line.LineStyle));
            
            #line default
            #line hidden
            this.Write(";\r\n    int lineThickness = ");
            
            #line 44 "D:\Repositories\paintc2.0\Paintc2.0\Paintc\Resources\RTT\CLineTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(line.LineThickness));
            
            #line default
            #line hidden
            this.Write(";\r\n\r\n    /* Establecer el grosor y estilo de la linea */\r\n    setlinestyle(lineSt" +
                    "yle, 0, lineThickness);\r\n    /* Establecer el color de la linea */\r\n    setcolor" +
                    "(color);\r\n    /* Dibujar la linea */\r\n    line(x1, y1, x2, y2);\r\n}\r\n\r\n");
            return this.GenerationEnvironment.ToString();
        }
        
        #line 54 "D:\Repositories\paintc2.0\Paintc2.0\Paintc\Resources\RTT\CLineTemplate.tt"
 
	public CLine line { get; set; }
    public CanvasSettings settings { get; set; }

        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
}
