// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 17.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Paintc.Resources.RTT
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using Shapes.C;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\Repositories\paintc2.0\Paintc2.0\Paintc\Resources\RTT\CPencilTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public partial class CPencilTemplate : BaseTemplate
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("/* Code generated by Paintc */\r\n#include <graphics.h>\r\n#include <conio.h>\r\n\r\n/* D" +
                    "ibuja ");
            
            #line 11 "D:\Repositories\paintc2.0\Paintc2.0\Paintc\Resources\RTT\CPencilTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(pencil.Name));
            
            #line default
            #line hidden
            this.Write(" */\r\nvoid draw_");
            
            #line 12 "D:\Repositories\paintc2.0\Paintc2.0\Paintc\Resources\RTT\CPencilTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(pencil.Name));
            
            #line default
            #line hidden
            this.Write(@"();

int main()
{
	int GraphDriver, GraphMode, ErrorCode;
	GraphDriver = DETECT; /* Request auto-detection	*/
	initgraph(&GraphDriver, &GraphMode, """");
	ErrorCode = graphresult(); /* Read result of initialization*/
	if (ErrorCode != grOk) /* Error occured during init	*/
	{ 
		printf("" Graphics System Error: %s\n"", grapherrormsg(ErrorCode));
		exit(1);
	}

	/* Establecer color de fondo */
	setbkcolor(");
            
            #line 27 "D:\Repositories\paintc2.0\Paintc2.0\Paintc\Resources\RTT\CPencilTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(settings.BackgroundColor));
            
            #line default
            #line hidden
            this.Write(");\r\n\r\n\t/* Your code here... */\r\n\tdraw_");
            
            #line 30 "D:\Repositories\paintc2.0\Paintc2.0\Paintc\Resources\RTT\CPencilTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(pencil.Name));
            
            #line default
            #line hidden
            this.Write("();\r\n\r\n\tgetch();\r\n\tclosegraph(); /* Return the system to text mode\t*/\r\n\treturn 0;" +
                    "\r\n}\r\n\r\nvoid draw_");
            
            #line 37 "D:\Repositories\paintc2.0\Paintc2.0\Paintc\Resources\RTT\CPencilTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(pencil.Name));
            
            #line default
            #line hidden
            this.Write("()\r\n{\r\n\t/* Dibujar trazo */\r\n\t");
            
            #line 40 "D:\Repositories\paintc2.0\Paintc2.0\Paintc\Resources\RTT\CPencilTemplate.tt"

    foreach (var pixel in pencil.Pixels)
    {
	
            
            #line default
            #line hidden
            this.Write("\tputpixel(");
            
            #line 44 "D:\Repositories\paintc2.0\Paintc2.0\Paintc\Resources\RTT\CPencilTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(pixel.X));
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 44 "D:\Repositories\paintc2.0\Paintc2.0\Paintc\Resources\RTT\CPencilTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(pixel.Y));
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 44 "D:\Repositories\paintc2.0\Paintc2.0\Paintc\Resources\RTT\CPencilTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(pixel.Color));
            
            #line default
            #line hidden
            this.Write(");\r\n\t");
            
            #line 45 "D:\Repositories\paintc2.0\Paintc2.0\Paintc\Resources\RTT\CPencilTemplate.tt"

    }
	
            
            #line default
            #line hidden
            this.Write("\r\n}\r\n\r\n");
            return this.GenerationEnvironment.ToString();
        }
        
        #line 51 "D:\Repositories\paintc2.0\Paintc2.0\Paintc\Resources\RTT\CPencilTemplate.tt"
 
	public CPencil pencil { get; set; }
	public CanvasSettings settings { get; set; }

        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
}
