using Paintc.Core;
using Paintc.Enums;
using Paintc.Shapes;

namespace Paintc.Factory
{
    public static class ShapeFactory
    {
        public static ShapeBase? Create(ToolType toolType, string? autoGeneratedName)
        {
            return toolType switch
            {
                ToolType.PolygonTool => new PolygonShape(autoGeneratedName),
                ToolType.PencilTool => new FreeShape(autoGeneratedName),
                ToolType.LineTool => new LineShape(autoGeneratedName),
                ToolType.RectangleTool => new RectangleShape(autoGeneratedName),
                ToolType.EllipseTool => new EllipseShape(autoGeneratedName),
                _ => null,
            };
        }
    }
}
